version: '3.9'
services:
  webdav:
    image: ghcr.io/hacdias/webdav:v5.11.10@sha256:2b708c56b4f36cd75c56d29f22ca1b7bd364782ee15c184182a4187a03538fde
    hostname: webdav
    container_name: webdav__webdav
    restart: unless-stopped

    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    volumes:
      - type: bind
        source: ./config.yml
        target: /config.yml
        read_only: true

      - type: bind
        source: /data/webdav
        target: /data

    command: -c /config.yml

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflared:
    image: cloudflare/cloudflared:2026.6.0-amd64@sha256:55d8bb268e90b09d3bf05a9bb5d3bc6ddad1b0b69739e4f15daaa7e6676238b6
    hostname: cloudflared
    container_name: webdav__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: webdav__default
