version: '3.9'
services:
  webdav:
    image: ghcr.io/hacdias/webdav:v5.16.1@sha256:9e53ecba84eab56583f42d5620f59e4c98cef34c807b17b1883c3ed0ccde4ee9
    hostname: webdav
    container_name: webdav__webdav
    restart: unless-stopped

    environment:
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    volumes:
      - type: bind
        source: ./config.yml
        target: /config.yml
        read_only: true

      - type: bind
        source: /data/webdav
        target: /data

    command: -c /config.yml

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

  cloudflared:
    image: cloudflare/cloudflared:2026.9.3-amd64@sha256:2fa795d0271a71c133a8f17c19a2a625e1976ad716329e0e61789f9fd8ee0091
    hostname: cloudflared
    container_name: webdav__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: webdav__default
